--- #YAML:1.0
name: Data-FormValidator-Tutorial
version: 1.60
author:
  - William McKee <william@knowmad.com>
  - Jason Purdy <jason@purdy.info>
abstract: Data::FormValidator Tutorial
license: perl
requires:
  perl: 5.6.1
provides:
  Data::FormValidator::Tutorial:
    file: lib/Data/FormValidator/Tutorial.pm
    version: 1.60
generated_by: Jason
